<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">R&Egrave;GLEMENT DU JEU-CONCOURS</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&laquo;&nbsp;La Saison des Artistes&nbsp;&raquo;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 1 &ndash; ORGANISATION DU JEU CONCOURS</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">MACIR VIE, soci&eacute;t&eacute; par action (SPA) au capital de&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1 395 000 000&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">DZD, dont le si&egrave;ge se trouve au 43 rue Belkacem AMANI, Paradou, Hydra, immatricul&eacute;e au Registre de Commerce d&rsquo;Alger sous le num&eacute;ro 11B0983849-00/16 (ci-apr&egrave;s la &laquo;&nbsp;soci&eacute;t&eacute; organisatrice&nbsp;&raquo; et repr&eacute;sent&eacute;e par Whiteline Services Soci&eacute;t&eacute; &agrave; Responsabilit&eacute; Limit&eacute;e, en sa qualit&eacute; d&rsquo;agence r&eacute;f&eacute;rente, agissant en tant que d&eacute;partement Marketing &amp; Communication pour le compte de MACIR VIE SPA.</span></p>
<p><br></p>
<ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:'Noto Sans Symbols',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: 36pt;">
        <p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Organise du&nbsp;:</span></p>
    </li>
</ul>
<p dir="ltr" style="line-height:1.3800000000000001;margin-left: 93pt;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">08/03/2021 au 20/03/2021 (inclus),</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">un jeu concours gratuit sans obligation d&rsquo;achat intitul&eacute;&nbsp;: &laquo;&nbsp;La Saison des Artistes&nbsp;&raquo; (ci-apr&egrave;s d&eacute;nomm&eacute; &laquo;&nbsp;le Concours&nbsp;&raquo;), selon les modalit&eacute;s d&eacute;crites dans le pr&eacute;sent r&egrave;glement.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ce Jeu est organis&eacute; sous forme de concours pour des artistes amateurs ou professionnels&nbsp;;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cette op&eacute;ration n&rsquo;est ni organis&eacute;e, ni parrain&eacute;e par Facebook.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Les donn&eacute;es personnelles collect&eacute;es dans le cadre du pr&eacute;sent Concours sont destin&eacute;es &agrave; la soci&eacute;t&eacute; organisatrice et non &agrave; Facebook.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 2 &ndash; CONDITIONS DE PARTICIPATION</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ce concours gratuit est ouvert &agrave; toute personne physique majeure&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ou mineure</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, disposant d&rsquo;un acc&egrave;s &agrave; internet, d&rsquo;une adresse &eacute;lectronique, d&rsquo;un num&eacute;ro de t&eacute;l&eacute;phone valide et de nationalit&eacute; alg&eacute;rienne,&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">dont le domicile est situ&eacute; en Alg&eacute;rie</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, &agrave; l&rsquo;exclusion des personnels de la soci&eacute;t&eacute; organisatrice,&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">de son repr&eacute;sentant Whiteline Services&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">et de leurs familles, ainsi que de toutes personnes ayant particip&eacute; &agrave; l&rsquo;&eacute;laboration du concours.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Les mineurs sont admis &agrave; participer au pr&eacute;sent concours, &agrave; condition qu&rsquo;ils aient pr&eacute;alablement obtenu de leurs parents ou de la personne exer&ccedil;ant l&rsquo;autorit&eacute; parentale l&rsquo;autorisation expresse de le faire. Le fait pour eux de participer &agrave; ce concours implique tacitement qu&rsquo;ils aient obtenu cette autorisation.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Le seul fait de participer &agrave; ce concours implique l&apos;acceptation pure et simple, sans r&eacute;serve, du pr&eacute;sent r&egrave;glement.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 3 &ndash; MODALIT&Eacute;S DE PARTICIPATION</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ce jeu est un concours de type &lsquo;&rsquo; S&eacute;lection par un comit&eacute; &lsquo;&rsquo; qui se d&eacute;roule exclusivement sur internet via l&rsquo;url&nbsp;:</span></p>
<ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
        <p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://www.macirvie.com/fr/saison-des-artistes</span></p>
    </li>
</ul>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">aux dates indiqu&eacute;es dans l&rsquo;article 1.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cette URL est accessible depuis le site&nbsp;</span><a href="http://www.macirvie.com" style="text-decoration:none;"><span style="font-size:12pt;font-family:Arial;color:#0000ff;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">www.macirvie.com</span></a><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;et les diff&eacute;rents r&eacute;seaux sociaux (Facebook, Twitter, Instagram et LinkedIn) de la soci&eacute;t&eacute;.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La participation au concours s&rsquo;effectue de la mani&egrave;re suivante :&nbsp;</span></p>
<ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
        <p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La personne doit envoyer une &oelig;uvre originale, compos&eacute;e et r&eacute;alis&eacute;e par elle-m&ecirc;me;</span></p>
    </li>
    <li aria-level="1" dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
        <p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">L&rsquo;&oelig;uvre doit &ecirc;tre num&eacute;ris&eacute;e (ou num&eacute;risable) et au format 22x11cm;</span></p>
    </li>
    <li aria-level="1" dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
        <p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La personne doit remplir le formulaire de participation mis &agrave; disposition des participants. Ce formulaire est accessible sur les URLs mentionn&eacute;es ci-dessus.</span></p>
    </li>
</ul>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Il n&rsquo;est autoris&eacute; qu&rsquo;une seule participation par personne -m&ecirc;me nom, m&ecirc;me pr&eacute;nom, m&ecirc;me adresse &eacute;lectronique, m&ecirc;me num&eacute;ro de t&eacute;l&eacute;phone - pendant toute la p&eacute;riode du Concours.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La soci&eacute;t&eacute; organisatrice se r&eacute;serve le droit de proc&eacute;der &agrave; toute v&eacute;rification pour le respect de cette r&egrave;gle.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Le Concours &eacute;tant accessible notamment sur la plateforme Facebook, www.facebook.com, en aucun cas Facebook ne sera tenu responsable en cas de litige li&eacute; au Jeu. Facebook n&apos;est ni organisateur ni parrain de l&apos;op&eacute;ration. Les donn&eacute;es personnelles collect&eacute;es lors du Concours sont destin&eacute;es &agrave; la soci&eacute;t&eacute; organisatrice conform&eacute;ment &agrave; l&rsquo;article 12 du pr&eacute;sent r&egrave;glement.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp;&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp;&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp;&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp;&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Le Concours &eacute;tant accessible sur t&eacute;l&eacute;phone mobile (Smartphone), en aucun cas Apple, Microsoft, Google o&ugrave; toute autre plateforme d&apos;application mobile ne seront tenus responsables en cas de litige li&eacute; au Jeu.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 4 &ndash; DESIGNATION DES GAGNANTS</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Un gagnant sera s&eacute;lectionn&eacute; par le comit&eacute; de s&eacute;lection apr&egrave;s la date de fin du Concours mentionn&eacute; dans l&rsquo;article 1 dans un d&eacute;lai de 7 jours maximum.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Le comit&eacute; d&eacute;terminera le gagnant parmi les participants ayant compl&eacute;t&eacute; et valid&eacute; le formulaire de participation.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Le gagnant sera contact&eacute; directement par mail ou par t&eacute;l&eacute;phone, par la Soci&eacute;t&eacute;&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Organisatrice&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">dans un d&eacute;lai de trois (03) jours apr&egrave;s la s&eacute;lection afin de proc&eacute;der &agrave; la remise du gain.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 5 &ndash; DOTATION</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Le Concours est dot&eacute; du gain suivant, attribu&eacute; &agrave; la personne d&eacute;clar&eacute;e gagnante,&nbsp;</span><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">en pr&eacute;sence d&rsquo;un huissier de justice</span><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;:</span></p>
<p><br></p>
<ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
        <p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Un ch&egrave;que de 100 000 DZD et une apparition de l&apos;&oelig;uvre sur la pochette de l&rsquo;assurance voyage de Macir Vie pendant une p&eacute;riode de 3 mois.</span></p>
    </li>
</ul>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La valeur du prix mis en jeu est d&eacute;termin&eacute;e au moment de l&rsquo;organisation du jeu-concours que r&eacute;git le pr&eacute;sent r&egrave;glement et ne saurait faire l&rsquo;objet d&rsquo;une contestation quant &agrave; son &eacute;valuation.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La soci&eacute;t&eacute; organisatrice se r&eacute;serve le droit de proc&eacute;der &agrave; la v&eacute;rification de l&rsquo;&acirc;ge de tout gagnant avant remise de son lot. La soci&eacute;t&eacute; organisatrice ne saurait &ecirc;tre tenue pour responsable de l&rsquo;utilisation ou de la non-utilisation du gain par le gagnant.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En cas de non-respect d&rsquo;une quelconque clause du pr&eacute;sent r&egrave;glement ou de force majeure, la soci&eacute;t&eacute; organisatrice se r&eacute;serve le droit d&rsquo;annuler le gain gagn&eacute; sans contrepartie.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 6 &ndash; IDENTIFICATION DES GAGNANTS ET ELIMINATION DE LA PARTICIPATION</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Les participants autorisent la v&eacute;rification de leur identit&eacute; et de toutes les informations figurant sur le formulaire de participation. Les participations dont le formulaire ne sera pas enti&egrave;rement rempli et/ou comportant des coordonn&eacute;es incompl&egrave;tes ou fausses ne seront pas prises en consid&eacute;ration et entra&icirc;nent l&rsquo;&eacute;limination de la participation.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">De m&ecirc;me, le non-respect du pr&eacute;sent r&egrave;glement ainsi que toute fraude ou tentative de tricherie, quelles que soient ses modalit&eacute;s, entra&icirc;nera l&rsquo;&eacute;limination pure et simple de la participation de son auteur.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 7 &ndash; MODIFICATION DES DATES DU CONCOURS ET &Eacute;LARGISSEMENT DU NOMBRE DE DOTATIONS</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La soci&eacute;t&eacute; organisatrice ne saurait encourir une quelconque responsabilit&eacute;, en cas de force majeure ou d&rsquo;&eacute;v&eacute;nements ind&eacute;pendants de sa volont&eacute; si elle &eacute;tait amen&eacute;e &agrave; annuler le pr&eacute;sent Concours. Elle se r&eacute;serve par ailleurs la possibilit&eacute; de prolonger ou de limiter la p&eacute;riode de participation, de le reporter ou en modifier les conditions, sa responsabilit&eacute; ne pouvant &ecirc;tre engag&eacute;e de ce fait.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Des additifs et modifications &agrave; ce r&egrave;glement peuvent &eacute;ventuellement &ecirc;tre publi&eacute;s pendant le Concours. Ils seront consid&eacute;r&eacute;s comme des annexes au pr&eacute;sent r&egrave;glement. Tout changement fera l&rsquo;objet d&rsquo;informations pr&eacute;alables par tout moyen appropri&eacute;.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 8 &ndash; UTILISATION DE L&apos;IDENTITE DES GAGNANTS</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vos donn&eacute;es personnelles sont trait&eacute;es par la Soci&eacute;t&eacute; Organisatrice, agissant en qualit&eacute; de destinataire et responsable de traitement, conform&eacute;ment &agrave; la r&eacute;glementation alg&eacute;rienne applicable en mati&egrave;re de protection des donn&eacute;es.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En remplissant le formulaire et en envoyant les documents requis pour assurer votre participation &agrave; notre Concours, vous consentez &agrave; ce que nous traitions et collections vos donn&eacute;es personnelles. Les donn&eacute;es personnelles recueillies sont obligatoires. Si vous ne fournissez pas les donn&eacute;es requises, vous ne pourrez pas participer au Concours.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Elles sont exclusivement destin&eacute;es &agrave; la Soci&eacute;t&eacute; Organisatrice aux seules fins de la prise en compte de votre participation au jeu, de la gestion des gagnants, de l&rsquo;attribution du gain et pour satisfaire aux obligations l&eacute;gales et r&eacute;glementaires. Vos donn&eacute;es pourront aussi &ecirc;tre utilis&eacute;es &agrave; des fins de prospection commerciale, sous r&eacute;serve de votre accord.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vos donn&eacute;es personnelles sont transf&eacute;r&eacute;es &agrave; nos services marketing et communication, ainsi qu&rsquo;aux prestataires de service et sous-traitants auxquels la Soci&eacute;t&eacute; Organisatrice ferait &eacute;ventuellement appel pour les besoins de l&rsquo;organisation et/ou de la gestion du jeu. Ces sous-traitants sont situ&eacute;s en Alg&eacute;rie.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vos donn&eacute;es personnelles seront imm&eacute;diatement supprim&eacute;es une fois le jeu arriv&eacute; &agrave; terme ou seront conserv&eacute;es pour une dur&eacute;e maximum de 3 ans si vous avez accept&eacute; l&rsquo;utilisation de vos donn&eacute;es &agrave; des fins de prospection commerciale. Ce d&eacute;lai pourra &ecirc;tre sup&eacute;rieur en cas de risque contentieux afin d&rsquo;assurer la d&eacute;fense de nos int&eacute;r&ecirc;ts.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vous pouvez retirer votre consentement &agrave; tout moment.&nbsp;</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vous disposez de droits d&rsquo;acc&egrave;s, de rectification, de suppression et &agrave; la portabilit&eacute; de vos donn&eacute;es, de limitation et d&rsquo;opposition au traitement de vos donn&eacute;es ainsi que du droit de d&eacute;finir des directives relatives au sort de vos donn&eacute;es personnelles apr&egrave;s votre d&eacute;c&egrave;s. Pour exercer ces droits, vous pouvez envoyer votre requ&ecirc;te &agrave; hello@macirvie.com.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 9 - RESPONSABILITES</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La participation implique la connaissance et l&rsquo;acceptation des caract&eacute;ristiques et des limites de l&rsquo;Internet, l&rsquo;absence de protection de certaines donn&eacute;es contre des d&eacute;tournements &eacute;ventuels ou piratage et risques de contamination par d&rsquo;&eacute;ventuels virus circulant sur le r&eacute;seau. La soci&eacute;t&eacute; organisatrice d&eacute;cline toute responsabilit&eacute; directe ou indirecte en cas de mauvaise utilisation ou d&rsquo;incident li&eacute; &agrave; l&rsquo;utilisation de l&rsquo;ordinateur, &agrave; l&rsquo;acc&egrave;s &agrave; Internet, &agrave; la maintenance ou &agrave; un dysfonctionnement des serveurs du Jeu, de la ligne t&eacute;l&eacute;phonique ou de toute autre connexion technique, &agrave; l&rsquo;envoi des formulaires &agrave; une adresse erron&eacute;e ou incompl&egrave;te.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Il appartient &agrave; tout participant de prendre toutes les mesures appropri&eacute;es de fa&ccedil;on &agrave; prot&eacute;ger ses propres donn&eacute;es et/ou logiciels stock&eacute;s sur son &eacute;quipement informatique contre toute atteinte.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La soci&eacute;t&eacute; organisatrice fournira ses meilleurs efforts pour permettre un acc&egrave;s au concours. La soci&eacute;t&eacute; organisatrice pourra, &agrave; tout moment, notamment pour des raisons techniques, de mise &agrave; jour, de maintenance, interrompre l&rsquo;acc&egrave;s au site et au concours. La soci&eacute;t&eacute; organisatrice ne sera en aucun cas responsable de ces interruptions et de leurs cons&eacute;quences. Aucune indemnit&eacute; ne pourra &ecirc;tre r&eacute;clam&eacute;e &agrave; ce titre.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En outre, la responsabilit&eacute; de la soci&eacute;t&eacute; organisatrice ne pourra en aucun cas &ecirc;tre retenue en cas de probl&egrave;mes d&apos;acheminement ou de perte de courrier postal ou &eacute;lectronique (notamment en ce qui concerne l&rsquo;acheminement des dotations). Tout gain envoy&eacute; par la soci&eacute;t&eacute; organisatrice &agrave; un gagnant qui serait non r&eacute;clam&eacute; ou retourn&eacute; pour toute autre raison par les services postaux serait perdu pour le gagnant et demeurerait acquis &agrave; la soci&eacute;t&eacute; organisatrice. La soci&eacute;t&eacute; organisatrice ne saurait &ecirc;tre tenue pour responsable du mauvais fonctionnement du r&eacute;seau Internet, ni de retard, perte ou avaries r&eacute;sultant des services postaux et de gestion.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 10 &ndash; DROITS DE PROPRI&Eacute;T&Eacute; INTELLECTUELLE, LITT&Eacute;RAIRE ET ARTISTIQUE</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Les images utilis&eacute;es sur le site du Concours, les objets repr&eacute;sent&eacute;s, les marques et d&eacute;nominations commerciales mentionn&eacute;es, les &eacute;l&eacute;ments graphiques, informatiques et les bases de donn&eacute;es composant le site du concours, sont la propri&eacute;t&eacute; exclusive de leurs titulaires respectifs et ne sauraient &ecirc;tre extraits, reproduits ou utilis&eacute;s sans l&apos;autorisation &eacute;crite de ces derniers, sous peine de poursuites civiles et/ou p&eacute;nales.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">L&rsquo;acceptation du pr&eacute;sent r&egrave;glement et des pr&eacute;sentes conditions vaut cession des droits de reproduction de l&apos;&oelig;uvre originale sur les supports mentionn&eacute;s dans le pr&eacute;sent document, pour la dur&eacute;e pr&eacute;vue &agrave; l&rsquo;article 5.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 11 &ndash; DONN&Eacute;ES PERSONNELLES</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La soci&eacute;t&eacute; organisatrice, son agence Whiteline Services, mettent en &oelig;uvre des traitements informatiques ayant pour finalit&eacute; la gestion&nbsp;du Jeu. La soci&eacute;t&eacute; organisatrice est responsable du traitement des donn&eacute;es personnelles pouvant &ecirc;tre collect&eacute;es.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Les donn&eacute;es personnelles collect&eacute;es seront utilis&eacute;es uniquement pour l&rsquo;organisation du Jeu. Si le participant en a fait le choix en cochant la case correspondante &agrave; l&rsquo;issue du questionnaire, son adresse email sera utilis&eacute;e pour lui envoyer la newsletter de MACIR VIE. Les donn&eacute;es collect&eacute;es seront conserv&eacute;es jusqu&apos;&agrave; ce que les gagnants aient &eacute;t&eacute; d&eacute;sign&eacute;s, puis d&eacute;truites, sauf si le participant a accept&eacute; que celles-ci soient conserv&eacute;es &agrave; des fins de prospection commerciale, auquel cas elles seront conserv&eacute;es pour une dur&eacute;e maximale de 1 an apr&egrave;s la derni&egrave;re sollicitation (prospect) ou r&eacute;servation (client).</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Les participants sont inform&eacute;s qu&rsquo;en acc&eacute;dant au site internet du Jeu, un cookie pourra le cas &eacute;ch&eacute;ant &ecirc;tre stock&eacute; sur le disque dur de leur ordinateur. Il s&apos;agit d&apos;un fichier informatique permettant d&apos;enregistrer leur navigation sur le site internet du Jeu. Les cookies servent &agrave; identifier chaque participant afin de lui permettre d&apos;acc&eacute;der plus rapidement aux informations, en lui &eacute;vitant de les ressaisir. Ils ne peuvent en aucun cas endommager les donn&eacute;es pr&eacute;sentes dans son ordinateur.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Un participant peut s&rsquo;opposer &agrave; l&apos;enregistrement de ce cookie, ou choisir d&apos;&ecirc;tre averti de l&apos;enregistrement de ce cookie sur son disque dur, en configurant son logiciel de navigation (le participant est invit&eacute; &agrave; se reporter aux conditions d&apos;utilisation de son navigateur concernant cette fonctionnalit&eacute;). Lorsque ce param&eacute;trage est effectu&eacute;, le participant garde n&eacute;anmoins la possibilit&eacute; d&apos;acc&eacute;der au site internet du Jeu et de participer &agrave; ce dernier.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Le participant peut acc&eacute;der aux informations le concernant en adressant un email &agrave; l&rsquo;adresse&nbsp;: hello@macirvie.com</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ARTICLE 12 &ndash; ATTRIBUTION DE COMP&Eacute;TENCE ET INTERPRETATION DU REGLEMENT</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:12pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Toute contestation &eacute;ventuelle sur l&rsquo;interpr&eacute;tation du r&egrave;glement sera tranch&eacute;e par la soci&eacute;t&eacute; organisatrice.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La participation &agrave; ce concours implique l&apos;acceptation sans r&eacute;serve (i) du pr&eacute;sent r&egrave;glement dans toutes ses stipulations, (ii) des r&egrave;gles d&eacute;ontologiques en vigueur sur Internet (&eacute;tiquette, charte de bonne conduite, etc...) ainsi que (iii) des lois et r&egrave;glements en vigueur sur le territoire Alg&eacute;rien et notamment des dispositions applicables aux jeux et loteries en vigueur. Il ne sera r&eacute;pondu &agrave; aucune demande t&eacute;l&eacute;phonique ou &eacute;crite concernant l&apos;interpr&eacute;tation ou l&apos;application du pr&eacute;sent r&egrave;glement, les m&eacute;canismes ou les modalit&eacute;s du jeu ainsi que sur la liste des gagnants. En cas de contestation, seul sera recevable un courrier en recommand&eacute; avec accus&eacute; de r&eacute;ception envoy&eacute; dans un d&eacute;lai de 30 jours maximum apr&egrave;s la date de fin du Concours. Sauf en cas d&apos;erreurs manifestes, il est convenu que les informations r&eacute;sultant des syst&egrave;mes de jeu de la soci&eacute;t&eacute; organisatrice ont force probante dans tout litige quant aux &eacute;l&eacute;ments de connexion et au traitement informatique desdites informations relatives au concours.</span></p>
<p><br></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Pr&eacute;alablement &agrave; toute action en justice li&eacute;e ou en rapport avec le pr&eacute;sent r&egrave;glement (en particulier son application ou son interpr&eacute;tation), les participants s&rsquo;engagent &agrave; former un recours amiable et gracieux aupr&egrave;s de la soci&eacute;t&eacute; organisatrice.</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Les participants sont soumis &agrave; la r&eacute;glementation alg&eacute;rienne applicable aux jeux et concours.&nbsp;</span></p>
<p dir="ltr" style="line-height:1.3800000000000001;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Tout litige qui ne pourra &ecirc;tre r&eacute;gl&eacute; &agrave; l&apos;amiable sera soumis aux tribunaux comp&eacute;tents dont d&eacute;pend le si&egrave;ge social de la soci&eacute;t&eacute; organisatrice, sauf dispositions d&apos;ordre public contraires.</span></p>
</body>

</html>
